name = Basic
description = A basic 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = basic-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer2]        = Footer 2

; Stylesheets
stylesheets[all][] = css/layouts/basic/basic.layout.css
